export const usersStorage = [
    {
        id: "1",
        profile: {
            id: 101,
            identification_type: "CC",
            name: "Jean",
            last_name: "Escobar",
            email: "jeanescobar7@hotmail.com",
            birth_date: "02/10/2002",
        },
        token: "abc123token",
        identification_number: "1007175382",
    },
    {
        id: "2",
        profile: {
            id: 102,
            identification_type: "CC",
            name: "María",
            last_name: "Gómez",
            email: "maria.gomez@example.com",
            birth_date: "20/08/1985",
        },
        token: "def456token",
        identification_number: "87654321",
    },
    {
        id: "3",
        profile: {
            id: 103,
            identification_type: "Pasaporte",
            name: "Carlos",
            last_name: "López",
            email: "carlos.lopez@example.com",
            birth_date: "30/11/1992",
        },
        token: "ghi789token",
        identification_number: "A1234567",
    },
    {
        id: "4",
        profile: {
            id: 104,
            identification_type: "CC",
            name: "Ana",
            last_name: "Martínez",
            email: "ana.martinez@example.com",
            birth_date: "10/03/1995",
        },
        token: "jkl012token",
        identification_number: "23456789",
    },
    {
        id: "5",
        profile: {
            id: 105,
            identification_type: "Pasaporte",
            name: "Luis",
            last_name: "Fernández",
            email: "luis.fernandez@example.com",
            birth_date: "25/07/1988",
        },
        token: "mno345token",
        identification_number: "B7654321",
    },
];

export const listAppointments = [
    {
        id: 20,
        date: "2025-04-03",
        time: "09:00 AM",
        doctor: "Carlos Navarro",
        location: "Hospital General",
    },
    {
        id: 19,
        date: "2025-04-06",
        time: "10:00 AM",
        doctor: "Ana Jiménez",
        location: "Clínica del Norte",
    },
    {
        id: 18,
        date: "2025-04-07",
        time: "11:00 AM",
        doctor: "Luis Flores",
        location: "Centro Médico",
    },
    {
        id: 17,
        date: "2023-10-17",
        time: "04:30 PM",
        doctor: "María Mendoza",
        location: "Hospital de la Ciudad",
    },
    {
        id: 16,
        date: "2023-10-16",
        time: "03:30 PM",
        doctor: "Jorge Ruiz",
        location: "Clínica Familiar",
    },
    {
        id: 15,
        date: "2023-10-15",
        time: "02:30 PM",
        doctor: "Sofía Ortiz",
        location: "Hospital Central",
    },
    {
        id: 14,
        date: "2023-10-14",
        time: "01:30 PM",
        doctor: "Diego Vega",
        location: "Clínica Sur",
    },
    {
        id: 13,
        date: "2023-10-13",
        time: "12:30 PM",
        doctor: "Laura Morales",
        location: "Hospital General",
    },
    {
        id: 12,
        date: "2023-10-12",
        time: "11:30 AM",
        doctor: "Pedro Castro",
        location: "Clínica del Norte",
    },
    {
        id: 11,
        date: "2023-10-11",
        time: "10:30 AM",
        doctor: "Elena Herrera",
        location: "Centro Médico",
    },
    {
        id: 10,
        date: "2023-10-10",
        time: "05:00 PM",
        doctor: "Ricardo Díaz",
        location: "Hospital de la Ciudad",
    },
    {
        id: 9,
        date: "2023-10-09",
        time: "04:00 PM",
        doctor: "Carmen Gómez",
        location: "Clínica Familiar",
    },
    {
        id: 8,
        date: "2023-10-08",
        time: "01:00 PM",
        doctor: "Héctor Sánchez",
        location: "Hospital Central",
    },
    {
        id: 7,
        date: "2023-10-07",
        time: "08:00 AM",
        doctor: "Patricia Torres",
        location: "Clínica Sur",
    },
    {
        id: 6,
        date: "2023-10-06",
        time: "03:00 PM",
        doctor: "Andrés Ramírez",
        location: "Hospital General",
    },
    {
        id: 5,
        date: "2023-10-05",
        time: "02:00 PM",
        doctor: "Gabriela Pérez",
        location: "Clínica del Norte",
    },
    {
        id: 4,
        date: "2023-10-04",
        time: "09:00 AM",
        doctor: "Fernando Martínez",
        location: "Centro Médico",
    },
    {
        id: 3,
        date: "2023-10-03",
        time: "12:00 PM",
        doctor: "Isabel López",
        location: "Hospital de la Ciudad",
    },
    {
        id: 2,
        date: "2023-10-02",
        time: "11:00 AM",
        doctor: "Roberto Fernández",
        location: "Clínica Familiar",
    },
    {
        id: 1,
        date: "2023-10-01",
        time: "10:00 AM",
        doctor: "Claudia García",
        location: "Hospital Central",
    },
];
