export const listUsers = [
    {
        id: "1",
        profile: {
            id: 101,
            identification_type: "CC",
            name: "Jean",
            last_name: "Escobar",
            email: "jeanescobar7@hotmail.com",
            birth_date: "02/10/2002",
        },
        token: "abc123token",
        identification_number: "1007175382",
    },
    {
        id: "2",
        profile: {
            id: 102,
            identification_type: "CC",
            name: "María",
            last_name: "Gómez",
            email: "maria.gomez@example.com",
            birth_date: "20/08/1985",
        },
        token: "def456token",
        identification_number: "87654321",
    },
    {
        id: "3",
        profile: {
            id: 103,
            identification_type: "Pasaporte",
            name: "Carlos",
            last_name: "López",
            email: "carlos.lopez@example.com",
            birth_date: "30/11/1992",
        },
        token: "ghi789token",
        identification_number: "A1234567",
    },
    {
        id: "4",
        profile: {
            id: 104,
            identification_type: "CC",
            name: "Ana",
            last_name: "Martínez",
            email: "ana.martinez@example.com",
            birth_date: "10/03/1995",
        },
        token: "jkl012token",
        identification_number: "23456789",
    },
    {
        id: "5",
        profile: {
            id: 105,
            identification_type: "Pasaporte",
            name: "Luis",
            last_name: "Fernández",
            email: "luis.fernandez@example.com",
            birth_date: "25/07/1988",
        },
        token: "mno345token",
        identification_number: "B7654321",
    },
];

export const listAppointments = [
    {
        id: 1,
        date: "2025-03-25",
        time: "09:00 AM",
        doctor: "Laura Mendoza",
        location: "Clínica Norte",
        status: "Confirmada",
    },
    {
        id: 2,
        date: "2025-03-26",
        time: "10:00 AM",
        doctor: "José Herrera",
        location: "Hospital Central",
        status: "Cancelada",
    },
    {
        id: 3,
        date: "2025-03-27",
        time: "11:30 AM",
        doctor: "Sofía Rodríguez",
        location: "Centro Médico",
        status: "Confirmada",
    },
    {
        id: 4,
        date: "2025-03-28",
        time: "01:00 PM",
        doctor: "Carlos Ramírez",
        location: "Clínica Sur",
        status: "Cancelada",
    },
    {
        id: 5,
        date: "2025-03-29",
        time: "02:00 PM",
        doctor: "Paula Vargas",
        location: "Hospital General",
        status: "Confirmada",
    },
    {
        id: 6,
        date: "2025-03-30",
        time: "03:00 PM",
        doctor: "Luis Torres",
        location: "Clínica Norte",
        status: "Confirmada",
    },
    {
        id: 7,
        date: "2025-03-31",
        time: "04:00 PM",
        doctor: "Camila Gómez",
        location: "Hospital de la Ciudad",
        status: "Confirmada",
    },
    {
        id: 8,
        date: "2025-04-01",
        time: "08:30 AM",
        doctor: "Andrés Morales",
        location: "Centro Médico",
        status: "Cancelada",
    },
    {
        id: 9,
        date: "2025-04-02",
        time: "10:30 AM",
        doctor: "Diana Paredes",
        location: "Hospital Central",
        status: "Confirmada",
    },
    {
        id: 10,
        date: "2025-04-03",
        time: "11:00 AM",
        doctor: "Rodrigo Fernández",
        location: "Clínica Familiar",
        status: "Confirmada",
    },
    {
        id: 11,
        date: "2025-04-04",
        time: "09:00 AM",
        doctor: "Marcela Díaz",
        location: "Clínica Sur",
        status: "Confirmada",
    },
    {
        id: 12,
        date: "2025-04-05",
        time: "10:00 AM",
        doctor: "Iván López",
        location: "Hospital General",
        status: "Cancelada",
    },
    {
        id: 13,
        date: "2025-04-06",
        time: "11:00 AM",
        doctor: "Natalia Ruiz",
        location: "Centro Médico",
        status: "Confirmada",
    },
    {
        id: 14,
        date: "2025-04-07",
        time: "02:00 PM",
        doctor: "Felipe Gutiérrez",
        location: "Clínica del Norte",
        status: "Confirmada",
    },
    {
        id: 15,
        date: "2025-04-08",
        time: "03:00 PM",
        doctor: "Estefanía Salas",
        location: "Hospital Central",
        status: "Cancelada",
    },
    {
        id: 16,
        date: "2025-04-09",
        time: "01:30 PM",
        doctor: "Miguel Castillo",
        location: "Clínica Sur",
        status: "Confirmada",
    },
    {
        id: 17,
        date: "2025-04-10",
        time: "12:00 PM",
        doctor: "Lorena Peña",
        location: "Hospital General",
        status: "Confirmada",
    },
    {
        id: 18,
        date: "2025-04-11",
        time: "10:00 AM",
        doctor: "Gustavo Márquez",
        location: "Clínica Familiar",
        status: "Confirmada",
    },
    {
        id: 19,
        date: "2025-04-12",
        time: "09:30 AM",
        doctor: "Elena Silva",
        location: "Hospital de la Ciudad",
        status: "Cancelada",
    },
    {
        id: 20,
        date: "2025-04-13",
        time: "11:30 AM",
        doctor: "Diego Blanco",
        location: "Centro Médico",
        status: "Confirmada",
    },
];
